version: '3.8'

networks:
  go-app:
    driver: bridge

services:
  app:
    container_name: golang-api
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./api:/usr/src/app/
    depends_on:
      - db
    networks:
      - go-app

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=golang_api
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - go-app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phymyadmin
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
      - PMA_PORT=3306
    restart: always
    ports:
      - "8085:80"
    volumes:
      - /sessions
    links:
      - db
    networks:
      - go-app

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - ./etc/localtime:/etc/localtime:ro
      - ./var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - "9000:9000"
    networks:
      - go-app

  cache:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - go-app