version: '3.8'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=golang_api
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phymyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    ports:
      - 8085:80
    volumes:
      - /sessions
    links:
      - db